# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic Publish'

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 1: Enable Corepack, which will automatically handle the Yarn version from package.json
      - name: Enable Corepack
        run: corepack enable

      # Step 2: Set up Node.js (this also handles caching of Yarn dependencies)
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      # Step 3: Install dependencies using the correct Yarn version
      - name: Install dependencies
        run: yarn install

      # Step 4: Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
